### ISSUE TITLE
ddns-service interval doesn't seem to work (only during startup)

### ISSUE THREAD

**Issue by ualex73** [marklagendijk/node-transip-dns-cli#1]
I am testing the Docker version and it works with DDNS updates when starting the container.

According to the information there is an interval of 5 minutes for re-check, only after 5 minutes nothing happens.

I am using the following command:
`command: ddns-service --username="myusername" --privateKeyFile="private-key.pem" --domainName="example.nl" --type="A"`

**Comment by ualex73** [comment]
Switched to something else what really work for me, closing this one.

**Comment by marklagendijk** [comment]
On startup you will see that it changes the dns record.
After that it will only output something if your ip address changed (or if there would be an error).
It only does an API call [when your ip address actually changed](https://github.com/marklagendijk/node-transip-dns-cli/blob/fa1a063274189522f871b65c2fb34fcd6cbb1947/bin/cli.js#L187).
