### ISSUE TITLE
Support IPv6 for DDNS 

### ISSUE THREAD

**Issue by johman10** [marklagendijk/node-transip-dns-cli#16]
When the client has an IPv6 address, the DDNS service will not be able to update. I think it's because of this line: https://github.com/marklagendijk/node-transip-dns-cli/blob/master/bin/cli.js#L227.

I think you should follow the same pattern as you do in other places within that file that will, based on the type of record, call the right function.

This is not a problem for me right now, I just went back to v4 for now, but perhaps something to consider adding support for. :D

Either way, thanks a lot of this project. It's exactly what I was looking for!

**Comment by Capusjon** [comment]
I think the support is already in the file. I'm by no means a coding guy but if I read on from line 296 it seems to me IPv6 is in there.

I haven't tried it out yet, if time allows i'll check it in the next couple of days.

@marklagendijk Thanks for this project. Got it up and running via docker and works as a charm. As we tend to say; "A kid can do the laundry" :)

**Comment by johman10** [comment]
You're right. I wasn't educated enough on the topic to open this issue but figured it out.

For future traceability: IPv6 addresses are stored in AAAA records and work perfectly fine with this tool.

Closing this issue.
